export const financialData = [
  {
    id: "11",
    transactionPrice: 28.75,
    transactionName: "Petro-Canada",
    transactionLocation: "Toronto, ON",
    transactionDate: "27th March, 2020",
  },
  {
    id: "12",
    transactionPrice: 14.99,
    transactionName: "Canadian Tire",
    transactionLocation: "Vancouver, BC",
    transactionDate: "28th March, 2020",
  },
  {
    id: "13",
    transactionPrice: 63.2,
    transactionName: "The Home Depot",
    transactionLocation: "Montreal, QC",
    transactionDate: "29th May, 2020",
  },
  {
    id: "14",
    transactionPrice: 37.5,
    transactionName: "Loblaws",
    transactionLocation: "Calgary, AB",
    transactionDate: "30th August, 2020",
  },
  {
    id: "15",
    transactionPrice: 45.8,
    transactionName: "Walmart",
    transactionLocation: "Edmonton, AB",
    transactionDate: "10th March, 2020",
  },
  {
    id: "16",
    transactionPrice: 20.45,
    transactionName: "Best Buy",
    transactionLocation: "Ottawa, ON",
    transactionDate: "1st April, 2020",
  },
  {
    id: "17",
    transactionPrice: 32.99,
    transactionName: "Costco",
    transactionLocation: "Mississauga, ON",
    transactionDate: "2nd April, 2020",
  },
  {
    id: "18",
    transactionPrice: 18.25,
    transactionName: "Staples",
    transactionLocation: "Winnipeg, MB",
    transactionDate: "3rd April, 2020",
  },
  {
    id: "19",
    transactionPrice: 55.6,
    transactionName: "Canadian Tire",
    transactionLocation: "Halifax, NS",
    transactionDate: "4th April, 2020",
  },
  {
    id: "20",
    transactionPrice: 9.99,
    transactionName: "Dollarama",
    transactionLocation: "Regina, SK",
    transactionDate: "5th April, 2020",
  },
  {
    id: "21",
    transactionPrice: 70.25,
    transactionName: "Shoppers Drug Mart",
    transactionLocation: "Victoria, BC",
    transactionDate: "6th April, 2020",
  },
  {
    id: "22",
    transactionPrice: 16.5,
    transactionName: "Indigo",
    transactionLocation: "London, ON",
    transactionDate: "7th April, 2020",
  },
];
